apiVersion: s3.aws.upbound.io/v1beta2
kind: Bucket
metadata:
  name: my-lens-crossplane-bucket-dev
spec:
  forProvider:
    region: us-east-1
  providerConfigRef:
    name: default
---
apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: my-crossplane-rg-dev
spec:
  forProvider:
    location: East US
  providerConfigRef:
    name: default
