config:
  global: {}
  route:
    receiver: 'slack-notifications'
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 1h
  receivers:
    - name: 'slack-notifications'
      slack_configs:
        - api_url: 'https://hooks.slack.com/services/dsasda'  # Your webhook
          send_resolved: true
          title: '{{ .CommonLabels.alertname }} ({{ .Status | toUpper }})'
          text: >-
            {{ range .Alerts }}
            *Alert:* {{ .Labels.alertname }}
            *Severity:* {{ if .Labels.severity }}{{ .Labels.severity }}{{ else }}n/a{{ end }}
            *Node:* {{ if .Labels.node }}{{ .Labels.node }}{{ else }}n/a{{ end }}
            *Namespace:* {{ if .Labels.namespace }}{{ .Labels.namespace }}{{ else }}n/a{{ end }}
            *Summary:* {{ if .Annotations.summary }}{{ .Annotations.summary }}{{ else }}n/a{{ end }}
            *Description:* {{ if .Annotations.description }}{{ .Annotations.description }}{{ else }}n/a{{ end }}
            {{- end }}